### ISSUE TITLE
[feat] 컨트롤과 제어변수 연결 및 smtp 서버 주소 자동 설정

### ISSUE THREAD

**Issue by yel-m** [yel-m/maily-christmas#3]
## Description

- 컨트롤을 제어변수와 연결하고 입력한 발신 메일 주소에 따라서 smtp 서버 주소를 자동으로 설정합니다.
- `전송` 버튼 클릭 시 성공 메시지 박스 생성
- 발신인, 수신인 미입력 시 에러 메시지 박스 생성

## TODO

- [x] 컨트롤을 제어변수와 연결
- [x] 입력한 발신 메일 주소에 따라서 smtp 서버 주소를 자동으로 설정합니다.
- [x] 성공 / 실패 메시지 박스 생성

## ETC
