### ISSUE TITLE
[feat] 비트맵 첨부 및 html 메일 전송

### ISSUE THREAD

**Issue by yel-m** [yel-m/maily-christmas#6]
## Description

다이얼로그에 편지지 비트맵 이미지를 첨부하고 html 메일 작성 및 전송 기능을 구현합니다. 

## TODO

- [x] 비트맵 첨부 및 다이얼로그에 띄우기
- [x] html 메일 포트, 제목, 호스트, 발신인, 수신인 설정 & 전송
- [x] 선택한 이미지에 따라 이미지 주소 다르게 설정
